<#
.SYNOPSIS
  Removes the WinUSB driver packages and certificates that the MarvinCapture installer
  created via libwdi (called by the uninstaller).

.DESCRIPTION
  1. Finds driver-store packages (C:\Windows\INF\oem*.inf) that were generated by libwdi
     (Provider = "libwdi") AND bind one of the five Marvin hardware IDs
     (USB\VID_2304&PID_0213/0223/0212/0224/0206). The vendor's MarvinAVS64.inf is never
     touched: it has a different provider. The INF text is parsed directly, so this does
     not depend on the language of pnputil's output.
  2. pnputil /delete-driver <oemNN.inf> /uninstall /force for each of them.
  3. Removes libwdi's auto-generated certificates ("CN=USB\VID_2304&PID_xxxx (libwdi
     autogenerated)", friendly name "libwdi") from LocalMachine Root and TrustedPublisher.
  4. pnputil /scan-devices, so Windows rebinds the device (to the vendor driver, if it is
     installed; otherwise the device stays without a driver until one is installed).

  Logs to -Log. Exit code 0 = nothing failed.

.PARAMETER Log  Log file (appended).
#>
[CmdletBinding()]
param(
    [string]$Log = (Join-Path $env:TEMP 'MarvinCapture-driver-uninstall.log')
)

$ErrorActionPreference = 'Stop'
$vid = '2304'
$pids = @('0213', '0223', '0212', '0224', '0206')
$pidAlt = ($pids -join '|')

function Write-Log([string]$msg) {
    $line = '{0:yyyy-MM-dd HH:mm:ss} {1}' -f (Get-Date), $msg
    try { Add-Content -LiteralPath $Log -Value $line -Encoding UTF8 } catch { }
    Write-Host $msg
}

function Get-NativeTool([string]$exe) {
    if ([Environment]::Is64BitOperatingSystem -and -not [Environment]::Is64BitProcess) {
        return (Join-Path $env:SystemRoot "sysnative\$exe")
    }
    return (Join-Path $env:SystemRoot "System32\$exe")
}

# Runs a native command without PowerShell turning stderr output into errors.
function Invoke-Native([string]$exe, [string[]]$arguments) {
    $old = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $out = & $exe @arguments 2>&1 | Out-String
        $rc = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $old
    }
    foreach ($l in ($out -split "`r?`n")) { if ($l.Trim()) { Write-Log ('  | ' + $l.Trim()) } }
    return $rc
}

# INF files written by libwdi are UTF-16 LE with BOM; others may be ANSI/UTF-8.
function Read-InfText([string]$path) {
    $b = [IO.File]::ReadAllBytes($path)
    if ($b.Length -ge 2 -and $b[0] -eq 0xFF -and $b[1] -eq 0xFE) {
        return [Text.Encoding]::Unicode.GetString($b, 2, $b.Length - 2)
    }
    if ($b.Length -ge 3 -and $b[0] -eq 0xEF -and $b[1] -eq 0xBB -and $b[2] -eq 0xBF) {
        return [Text.Encoding]::UTF8.GetString($b, 3, $b.Length - 3)
    }
    return ([Text.Encoding]::UTF8.GetString($b)) -replace "`0", ''
}

$failed = 0
try {
    Write-Log '== MarvinCapture: removing libwdi WinUSB driver packages and certificates'
    $pnputil = Get-NativeTool 'pnputil.exe'

    # --- 1. driver packages -------------------------------------------------------
    $found = @()
    $infDir = Join-Path $env:SystemRoot 'INF'
    foreach ($f in (Get-ChildItem -LiteralPath $infDir -Filter 'oem*.inf' -ErrorAction SilentlyContinue)) {
        try {
            $t = Read-InfText $f.FullName
        } catch {
            Write-Log "  cannot read $($f.Name): $($_.Exception.Message)"
            continue
        }
        # libwdi's template: Provider = "libwdi"; [Strings] DeviceID = "VID_2304&PID_0213"
        if ($t -match '(?im)^\s*Provider\s*=\s*"?libwdi"?\s*$' -and
            $t -match ('(?im)^\s*DeviceID\s*=\s*"VID_{0}&PID_({1})"' -f $vid, $pidAlt)) {
            $found += $f.Name
        }
    }
    if ($found.Count -eq 0) {
        Write-Log 'No libwdi driver packages for these devices in the driver store.'
    }
    foreach ($inf in $found) {
        Write-Log "Deleting driver package $inf"
        $rc = Invoke-Native $pnputil @('/delete-driver', $inf, '/uninstall', '/force')
        if ($rc -ne 0 -and $rc -ne 3010) {
            Write-Log "  pnputil failed for $inf (exit code $rc)"
            $failed++
        } else {
            Write-Log "  removed (exit code $rc)"
        }
    }

    # --- 2. certificates ----------------------------------------------------------
    foreach ($storeName in @('Root', 'TrustedPublisher')) {
        $store = "Cert:\LocalMachine\$storeName"
        $certs = @(Get-ChildItem -Path $store -ErrorAction SilentlyContinue | Where-Object {
            $_.Subject -match 'libwdi autogenerated' -and $_.Subject -match "VID_$vid&PID_($pidAlt)"
        })
        foreach ($c in $certs) {
            try {
                Remove-Item -LiteralPath (Join-Path $store $c.Thumbprint) -Force
                Write-Log "Removed certificate '$($c.Subject)' from $storeName"
            } catch {
                Write-Log "  could not remove certificate from ${storeName}: $($_.Exception.Message)"
                $failed++
            }
        }
        if ($certs.Count -eq 0) { Write-Log "No libwdi certificates for these devices in $storeName." }
    }

    # --- 3. let Windows rebind the devices ------------------------------------------
    $null = Invoke-Native $pnputil @('/scan-devices')
} catch {
    Write-Log "FAILED: $($_.Exception.Message)"
    $failed++
}
Write-Log ("Done, {0} problem(s)." -f $failed)
if ($failed -gt 0) { exit 1 }
exit 0
